<template lang="pug">
  .modal-wrapper(v-if="getPolicyStatus")
    .modal.modal-policy
      svg(@click="closeModalPolicy" class="modal--close" width='40', height='40', viewbox='0 0 40 40', fill='none', xmlns='http://www.w3.org/2000/svg')
        path(d='M6.01428 5.69443L34.6831 33.5889', stroke='black')
        path(d='M33.9473 5.66559L6.05283 34.3344', stroke='black')

      h3.modal-tos--subtitle Privacy Policy
      p.modal-tos--text Your privacy is important to us. We have prepared this Privacy Policy to explain how we collect, use, protect, and disclose Personal Information and Usage Data when you use the Sneakerdraws services ("Service"). This Privacy Policy also explains your choices for managing your information and your preferences. 
      p.modal-tos--text This Privacy Policy may be revised from time to time. By using the Service, you agree to be bound and to abide by the most recent version of this Privacy Policy. This Privacy Policy was last updated on 20/03/2020. 
      h3.modal-tos--subtitle GDPR Compliance
      p.modal-tos--text Sneakerdraws is a data controller and processor under the Regulation (EU) 2016/679 (General Data Protection Regulation, "GDPR"). Sneakerdraws has adopted the following policy concerning protection of personal data in accordance with the GDPR. Sneakerdraws will respond promptly to any requests concerning Sneakerdraws users rights to the protection of personal data.
      h3.modal-tos--subtitle Managing Your Information Preferences 
      p.modal-tos--text You can review, correct, update or delete your Personal Information, or opt out of any direct marketing in which we may engage, by e-mailing us at mail@sneakerdraws.com. If you have questions or concerns regarding this Privacy Policy, please e-mail us at mail@sneakerdraws.com with subject "LEGAL".
      h3.modal-tos--subtitle Information We Collect and How We Collect It 
      p.modal-tos--text Personal Information. You can use certain features of the Service without providing us with any information that identifies or may be used to directly identify you ("Personal Information"). 
      p.modal-tos--text We collect Personal Information when you register with Sneakerdraws: <br> - your username, <br> - e-mail address. 
      p.modal-tos--text We also collect Personal Information when you pay for Sneakerdraws subscription via Stripe or PayPal. 
      p.modal-tos--text We collect Personal Information only if you choose to share it with us. The decision to provide this information is optional. However, if you choose not provide the requested information, you may not be able to use certain features of the Service.
      p.modal-tos--text Usage Data. We automatically collect usage information that does not directly identify an individual user ("Usage Data"). For example, each time you use the Service we may automatically collect the type of Web browser you use, your operating system, your Internet Service Provider, your IP address, the links you use, and the time and duration of your use of the Service. We use this Usage Data to help us understand how people use the Service, and to enhance the services we offer. None of this information can be used to directly identify you, and we will not use it for the purpose of attempting to identify you. Please be aware, however, that we may be required by authorities to disclose information such as your IP address (a unique numerical identifier for your computer that may or may not change over time) which could be used by authorities to identify you. 
      p.modal-tos--text Cookies and Web Beacons. We use cookies (a small text file placed on your computer to identify your computer and Web browser when you use the Service). We may also use Web beacons (an electronic file placed on a website that monitors usage). We do not use cookies or Web beacons to collect Personal Information. We use cookies and Web beacons to improve the quality of the Service. Most Web browsers are initially set up to accept cookies. You can reset your Web browser to refuse all cookies or to indicate when a cookie is being sent. However, certain features of the Service may not work if you delete or disable cookies. Some of our Service Providers, as discussed below, may use their own cookies or Web beacons in connection with the services they perform on our behalf. 
      p.modal-tos--text Storage of Information. The information Sneakerdraws collects about you and your usage of the Service will be transmitted to and stored by Sneakerdraws on servers. 
      h3.modal-tos--subtitle How We Use Information and When We May Share Information
      p.modal-tos--text Generally. We generally use Personal Information only for purposes of providing and communicating with you about the Service, including responding to your requests, making payments, notifying you of new products or services, and otherwise communicating with you about the Service. We will not disclose Personal Information to third parties without your consent, except as explained in this Privacy Policy. 
      p.modal-tos--text Service Providers. From time to time, we may establish a business relationship with other businesses whom we believe trustworthy and who have confirmed that their privacy practices are consistent with ours ("Service Providers"). For example, we may contract with Service Providers to provide services such as payment processing, maintenance and support, data storage and management, advertising, and marketing. We provide our Service Providers with only the information necessary for them to perform these services on our behalf. Each Service Provider must agree to use reasonable security procedures and practices, appropriate to the nature of the information involved, in order to protect your Personal Information from unauthorized access, use, or disclosure. Service Providers are prohibited from using Personal Information other than as specified by Sneakerdraws.
      p.modal-tos--text Please note that when you make payments to Sneakerdraws, the information you provide is submitted to a third-party payment provider. It is not received or maintained by Sneakerdraws, except that your e-mail address will automatically be provided to us when you first pay for a Subscription, so that we can establish your account and provide you with the special features offered to Subscription holders.
      p.modal-tos--text You can request anytime a report to learn whether and what Personal Information you provided has been shared with Service Providers. 
      p.modal-tos--text Google Analytics. We also use Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies," which are text files placed on your computer, to help Sneakerdraws analyze how users use our Service. We use this information to help us understand how people use the Service, and to enhance the services we offer. The information generated by the cookie about your use of the Service (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the Service, compiling reports on Service activity for us, and providing other services relating to Service activity and Internet usage. Google may also transfer this information to third parties where required to do so by law, or if such third parties process the information on Google's behalf. Google will not associate your IP address with any other data held by Google. As noted, you may refuse the use of cookies by selecting the appropriate settings on your Web browser, but please note that if you do this you may not be able to use the full functionality of the Service. By using the Service, you consent to the processing of data about you by Google in the manner and for the purposes set out above. For more information, please visit 
      p.modal-tos--text http://www.google.com/analytics/en-GB/tos.html
      p.modal-tos--text Standard Analytics Information. We may use, and disclose to third parties, certain Usage Data regarding the Service. However, such information does not identify you individually. 
      p.modal-tos--text Other Transfers. We may share Personal Information and Usage Data with businesses controlling, controlled by, or under common control with Sneakerdraws. If Sneakerdraws is merged, acquired, or sold, or in the event of a transfer of some or all of our assets, we may disclose or transfer Personal Information and Usage Data in connection with such transaction. You will have the opportunity to opt-out of any such transfer if we determine, in our discretion, that the new entity plans to handle your information in a way that differs materially from this Privacy Policy. 
      p.modal-tos--text Data Retention. We will hold your Personal Information on our systems for as long as is necessary for the relevant activity. If you cancel your registration and your account is deleted Sneakerdraws will no longer use the Personal Information, but for administration purposes, it will stay on our system for a period of one year by default before being deleted. Personal Information would be deleted immediately on your request.
      p.modal-tos--text Compliance with Laws and Law Enforcement. Sneakerdraws cooperates with government and law enforcement officials and private parties to enforce and comply with the law. We may disclose Personal Information and any other information about you to government or law enforcement officials or private parties if, in our discretion, we believe it is necessary or appropriate for any of the following reasons: to respond to legal requests (including court orders and subpoenas); to protect the safety, property, or rights of Sneakerdraws, any Sneakerdraws user, or any third party; to prevent or stop any illegal, unethical, or legally actionable activity; or to comply with the law. 
      h3.modal-tos--subtitle Security
      p.modal-tos--text Sneakerdraws is very concerned about safeguarding the confidentiality of your Personal Information. We employ reasonable physical and electronic measures designed to protect your information from unauthorized access. However, no data transmission over the Internet or other network can be guaranteed to be 100% secure. As a result, while we strive to protect information transmitted on or through the Service, we cannot and do not guarantee the security of any information you upload, store, share, transmit, or provide on or through the Service, and you do so at your own risk. 
      h3.modal-tos--subtitle Children's Privacy 
      p.modal-tos--text We do not knowingly collect Personal Information from users under the age of 16. By using our Services, you promise that you are at least 16 years old. If we become aware that a user is under the age of 16, we will terminate any account that user may have with Sneakerdraws. If we become aware that we have inadvertently received Personal Information from a user under the age of 16, we will delete such information from our records.

</template>

<script>
export default {
  name: 'c_ModalPolicy',
  computed: {
    getPolicyStatus() {
      return this.$store.getters.getPolicyModalStatus
    }
  },
  methods: {
    closeModalPolicy() {
      this.$store.dispatch('policyModal', false)
    }
  }
}
</script>