<template lang="pug">
  .modal-wrapper(v-if="getModalTos")
    .modal.modal-tos
      svg(@click="closeModalTos" class="modal--close" width='40', height='40', viewbox='0 0 40 40', fill='none', xmlns='http://www.w3.org/2000/svg')
        path(d='M6.01428 5.69443L34.6831 33.5889', stroke='black')
        path(d='M33.9473 5.66559L6.05283 34.3344', stroke='black')

      p.modal-tos--text Welcome to Sneakerdraws a groundbreaking way of organizing, participating and most important winning sneaker raffles. 
      p.modal-tos--text Please read these Terms of Service (the "Terms") carefully before using the services (as defined below) offered by Buseedo SAS (the creators of Sneakerdraws). 
      p.modal-tos--text This text explains the terms by which you may use our online and mobile services, website sneakerdraws.com, and software provided on or in connection with the service (collectively the "Services"). By accessing or using these Services, you acknowledge and agree to these Terms and the Privacy Policy of Sneakerdraws. These Terms apply to all users of these Services. If you do not agree to these Terms, please do not use these Services.
      p.modal-tos--text We may, at our sole discretion, modify these Terms of Service at any time. By accessing the Service at any time after such modifications, you are agreeing to such modifications. These Terms of Service were last modified as of 20 March, 2020. 
      p.modal-tos--text We reserve the right to refuse to provide the Service to any person for any reason and/or to discontinue the Service in whole or in part at any time, with or without prior notice. 
      h3.modal-tos--subtitle Registration and Your Personal Information 
      p.modal-tos--text If you want to use these Services you have to sign up to our platform, newsletter (optional) and pay for your subscription (optional). Then you gain access to our website and mobile application. We use certain personal information Name, Surname, National ID number, email and in (some cases) address to prevent “bot” (robotic) entries in order to give real people real chances.
      h3.modal-tos--subtitle Sneakerdraws Services 
      p.modal-tos--text Please notice, that at this moment of time Sneakerdraws is in Beta status (as of 20 March 2020) and until further notice, which means it's still in development and you're signing up to be an early adopter of the product. So it may not represent all features described in promo materials, such as videos, pictures and/or text advertisements and meet your certain expectations right away.  Paid subscribers receive access to the paid features within 5 business days. We use email newsletters, mobile app and website to deliver the information about sneaker raffles and other offerings. Users can choose the way how to stay up to date with the latest news.
      h3.moda-tos--subtitle Rights to these Services 
      p.modal-tos--text Subject to your compliance with these Terms, we grant you a limited non-exclusive, non-transferable, non-sublicensable license to access these Services on your mobile device to access and use the application and the website, only in connection with the Services. Except as expressly and unambiguously granted herein, no right or license is granted. All suspicious actions with the use of any computer code, data mining software, "robot", "bot", "spider", "scraper" or other automatic devices, or programs, algorithms or methodologies having similar processes or functionality, or any manual process, to monitor or copy any of the web pages, data or content found on this Site or App, or accessed through this Site or App. actions will be investigated and may cause immediate agreement termination with any user.
      h3.modal-tos--subtitle User Feedback 
      p.modal-tos--text We welcome feedback, comments, and suggestions for improvements to these Services ("Feedback"), but you should understand that we may use your Feedback without any obligation to compensate you for them (just as you have no obligation to offer them). 
      h3.modal-tos--subtitle Our Proprietary Rights 
      p.modal-tos--text These Services and all materials therein, including software, images, text, graphics, illustrations, logos, patents, trademarks, service marks (the "Sneakerdraws Content"), and all intellectual property rights related thereto, are the exclusive property. You acknowledge that applicable copyright, trademark, and other laws protect these Services and Sneakerdraws Content. Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, non-sublicensable license to access and view the Sneakerdraws Content solely in connection with your permitted use of these Services and solely for your personal and non-commercial purposes. Use of these Services and Sneakerdraws Content for any purpose not expressly permitted by these Terms is strictly prohibited. Images of sneakers used for raffles on Sneakerdraws.com are the intellectual property of the mentioned in a raffle description creators/companies.
      h3.modal-tos--subtitle Fees and Plans
      p.modal-tos--text We reserve the right, at any time, to change any fees or charges for using any services provided on the Service (or to begin charging fees for any free service) without notification, provided that such changes will not apply to fees or charges paid or free services used prior to the time of the change. No refunds are offered for paid subscription fees or any other fees collected by the Service. 
      h3.modal-tos--subtitle Safety
      p.modal-tos--text We have the right to monitor the use of and access to these Services for the purpose of operating these Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. We can remove or temporarily ban any account at any time and without notice if we believe that it violates these Terms or our Privacy Policy. 
      h3.modal-tos--subtitle Indemnity
      p.modal-tos--text INDEMNIFICATION AND LIMITATION OF LIABILITY TO APPLE INC. The promotions, products, and services offered as part of this Application are operated independently of Apple Inc. and are in no way associated with, endorsed by, or affiliated with Apple Inc.
      p.modal-tos--text You will indemnify and hold harmless Sneakerdraws and its officers, directors, employees, and agents, from and against any claims, disputes, demands, liabilities, damages, costs and expenses, and losses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with: (i) your use of or access to these Services; (ii) your violation of these Terms. 
      h3.modal-tos--subtitle Warranty Disclaimers and Limitation of Liability 
      p.modal-tos--text WE WILL TRY TO KEEP Sneakerdraws UP AND RUNNING, BUG-FREE, AND SAFE, BUT YOU USE IT AT YOUR OWN RISK. WE DO NOT GUARANTEE THAT Sneakerdraws WILL ALWAYS BE SAFE, SECURE, ERROR-FREE, OR THAT Sneakerdraws WILL ALWAYS FUNCTION WITHOUT DISRUPTIONS, DELAYS, OR IMPERFECTIONS. THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. Sneakerdraws DOES NOT WARRANT THAT THE SERVICE WILL MEET BUSINESS'S REQUIREMENTS OR RESULT IN ANY OUTCOME, OR THAT THE OPERATION OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE. EXCEPT AS OTHERWISE EXPRESSLY PROVIDED HEREIN, TO THE FULLEST EXTENT PERMITTED BY LAW, Sneakerdraws HEREBY DISCLAIMS ALL OTHER WARRANTIES, WHETHER EXPRESS OR IMPLIED, ORAL OR WRITTEN, WITH RESPECT TO THE SERVICE INCLUDING, WITHOUT LIMITATION, ALL IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, QUIET ENJOYMENT, INTEGRATION, MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE. EXCEPT TO THE EXTENT THAT ANY EXCLUSION OR LIMITATION OF ITS LIABILITY IS VOID, PROHIBITED OR UNENFORCEABLE BY APPLICABLE LAW, In no event shall Sneakerdraws BE LIABLE CONCERNING THE SUBJECT MATTER OF this agreement, regardless of the form of any claim or action (whether in CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE), for any (A) MATTER BEYOND ITS REASONABLE CONTROL (INCLUDING ANY ERROR OR DAMAGE ATTRIBUTABLE TO ANY NETWORK OR SYSTEM), (B) LOSS OR INACCURACY of data, loss or interruption OF USE, OR COST OF PROCURING SUBSTITUTE TECHNOLOGY, GOODS or SERVICE, (C) INDIRECT, PUNITIVE, INCIDENTAL, RELIANCE, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO, LOSS OF BUSINESS, REVENUES, PROFITS AND GOODWILL, AND TRADING AND INVESTMENT LOSSES, OR (D) damages, IN THE AGGREGATE, in excess of the greater of $1000 or the fees paid by User hereunder in the SIX (6) MONTHS preceding the applicable claim, EVEN IF Sneakerdraws HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THESE LIMITATIONS ARE INDEPENDENT OF ALL OTHER PROVISIONS OF THIS AGREEMENT AND SHALL APPLY NOTWITHSTANDING THE FAILURE OF ANY REMEDY PROVIDED HEREIN. PLEASE NOTICE, THAT WE DO NOT GUARANTEE AN EMPLOYMENT NEITHER IN NORTH AMERICA (USA/CANADA) NOR IN EUROPE. ALL FEEDBACK, TIPS & ADVICE PROVIDED VIA Sneakerdraws Services SHOULD BE CONSIDERED AS RECOMMENDATIONS ONLY. IF USER WINS IN THE RAFFLE WE DO NOT GUARANTEE THAT USER GETS IT. ALL QUESTIONS REGARDING ORDER FULFILLMENT MUST BE ADDRESSED TO PARTICIPATING STORES. 
      h3.modal-tos--subtitle General Terms
      p.modal-tos--text If any portion of these Terms is found to be unenforceable, the remaining portion will remain in full force and effect. If we fail to enforce any of these Terms, it will not be considered a waiver. We may, in our sole discretion, modify these Terms at any time, and it is your responsibility to review these Terms for any changes. Your continued use of these Services after any such change constitutes your acceptance of the new Terms of Use. If you do not agree to any of these Terms or any future Terms of Use, do not use, access, or continue to access these Services. You may not assign or transfer these Terms without Sneakerdraws' prior written consent. Sneakerdraws may freely assign or transfer these Terms without restriction. Any notices or other communications provided by Sneakerdraws under these Terms, including those regarding modifications to these Terms, will be posted to these Services. 
      p.modal-tos--text Please note, that USERS do not purchase products (sneakers, clothing and etc.) from Sneakerdraws, and are not charged for the products in the app or the website. All raffle winners using Sneakerdraws are purchasing directly from the participating retailer and must be paid for in-store on release day. Sneakerdraws is strictly a reservation service and is not responsible for the fulfillment of the participating retailer. Any complaints regarding discrepancies or irregularities with the purchase must be addressed to the participating retailer. All raffle wins that came through the Services are subject to Sneakerdraws’ acceptance and confirmation. Sneakerdraws may refuse to accept or may void any winning entry, whether or not the W has been confirmed, for any or no reason, and without liability to you or anyone else. 
      h3.modal-tos--subtitle Contact Information
      p.modal-tos--address If you have any questions about these Terms and Services, please contact us at mail@sneakerdraws.com or send us a letter to our business address:
      p.modal-tos--address BUSEEDO SAS
      p.modal-tos--address 1 boulevard Victor, 75015, Paris, France.
</template>

<script>
export default {
  name: 'c_ModalTos',
  computed: {
    getModalTos() {
      return this.$store.getters.getTosModalStatus
    }
  },
  methods: {
    closeModalTos() {
      this.$store.dispatch('tosModal', false)
    }
  }
}
</script>